version: '3.8'

services:
  web:
    build: .
    ports:
     - "8008:5000"
  mongodb:
    image: mongo
    command: --auth
    volumes:
      - ./mongodb.key:/etc/ssl/mongodb.key:ro
      - ./data:/data/db
      - ./src//mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_ROOT_ROLE: root
      MONGO_INITDB_ARGS: --encryption --encryptionKeyFile /etc/ssl/mongodb.key
      MONGO_INITDB_DATABASE: studies
    ports:
    - 27017:27017
