version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./data:/app/data
      - ./cfg:/app/cfg
    ports:
     - "8080:8080"
    depends_on:
      - database
#  database:
#    image: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres