version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./data:/app/data
    ports:
     - "8080:8080"
  database:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres